const SALIR = "SALIR";
const INTEREST = 5;
const MAXINSTALLMENTS = 60;
const MINISTALLMENTS = 1;
export const URLAPI="https://6343977b2dadea1175a9e0ed.mockapi.io/"


 export{SALIR,INTEREST,MAXINSTALLMENTS,MINISTALLMENTS};
 